# Generated by Django 4.1.4 on 2022-12-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='search_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
