# Generated by Django 4.1.4 on 2022-12-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_alter_airport_search_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='search_name',
            new_name='search_field',
        ),
    ]
