# Generated by Django 4.1.4 on 2022-12-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_rename_search_name_airport_search_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='airport_name',
            new_name='display_name',
        ),
    ]
