# Generated by Django 4.1.3 on 2022-11-15 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.ForeignKey(default='850e92dd-a12d-4c58-94ef-782ec4c4edc7', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.item')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
