# Generated by Django 4.1.3 on 2022-11-15 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non binary'), ('O', 'Other')], max_length=1)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('web_site', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_status', models.ForeignKey(default='69e5e698-a900-4d14-a077-ba165f476a40', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.item')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_country', to='catalogue.item')),
                ('phone_contry_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_phone_contry_code', to='catalogue.item')),
            ],
            options={
                'db_table': 'agents',
                'managed': True,
            },
        ),
    ]
