# Generated by Django 4.1.3 on 2022-11-15 10:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_alter_item_metadata'),
        ('user', '0002_user_is_active_alter_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non binary'), ('O', 'Other')], max_length=1)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('web_page', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='country', to='catalogue.item')),
                ('phone_contry_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phone_contry_code', to='catalogue.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'agents',
                'managed': True,
            },
        ),
    ]
