# Generated by Django 4.1.3 on 2022-11-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='favorite_food',
            field=models.CharField(default='Pizza', max_length=100),
        ),
    ]
