# Generated by Django 4.1.3 on 2022-11-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='web_page',
            new_name='web_site',
        ),
    ]
