# Generated by Django 4.1.3 on 2022-11-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_rename_phone_contry_code_agent_phone_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='favorite_food',
        ),
    ]
