# Generated by Django 4.1.3 on 2022-11-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_catalogue_options_alter_item_options'),
        ('agent', '0004_remove_agent_favorite_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone_country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_phone_country_code', to='catalogue.item'),
        ),
    ]
