# Generated by Django 4.1.3 on 2022-11-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_description',
        ),
    ]
