# Generated by Django 4.1.3 on 2022-11-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_reservation_room_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationpayment',
            old_name='aproved_at',
            new_name='approved_at',
        ),
    ]
