# Generated by Django 4.1.3 on 2022-11-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_amount_alter_payment_commission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalagent',
            old_name='telephone',
            new_name='phone_number',
        ),
    ]
