# Generated by Django 4.1.3 on 2022-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_telephone_externalagent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalagent',
            name='external_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
