# Generated by Django 4.1.3 on 2022-11-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_agent_agent_status_alter_agent_country_and_more'),
        ('payment', '0003_rename_aproved_at_reservationpayment_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='payment.reservationpayment'),
        ),
        migrations.AlterField(
            model_name='reservationpayment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agent.agent'),
        ),
    ]
