# Generated by Django 4.1.3 on 2022-11-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_externalagent_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalagent',
            name='external_id',
            field=models.CharField(max_length=40),
        ),
    ]
