# Generated by Django 4.1.3 on 2022-11-27 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('payment', '0005_alter_externalagent_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aproved_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='agent.agent')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_rooms',
        ),
        migrations.DeleteModel(
            name='ExternalAgent',
        ),
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='payment.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='payment.reservationpayment'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
