# Generated by Django 4.1.3 on 2022-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_reservation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('CH', 'Child')], default='MR', max_length=2),
        ),
    ]
