# Generated by Django 4.1.3 on 2022-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_reservationpayment_room_remove_payment_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
