# Generated by Django 4.1.3 on 2022-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_guest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationpayment',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
