# Generated by Django 4.1.3 on 2022-11-08 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=40, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'catalogs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=40, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('metadata', models.JSONField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.catalog')),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
    ]
