# Generated by Django 4.1.5 on 2023-01-09 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=400)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('notification_type', models.CharField(choices=[('P', 'pop_up'), ('F', 'feed')], max_length=1)),
                ('read', models.BooleanField(default=False)),
                ('action', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='agent.agent')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notification',
                'db_table': 'notifications',
                'managed': True,
            },
        ),
    ]
