# Generated by Django 4.1.5 on 2023-01-09 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=400)),
                ('company_address', models.CharField(max_length=400)),
                ('account_number', models.CharField(max_length=40)),
                ('account_clabe', models.CharField(max_length=40)),
                ('bank_name', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'bank_accounts',
                'managed': True,
            },
        ),
    ]
