# Generated by Django 4.1.3 on 2022-12-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_api', '0002_remove_externaldestination_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalDestination',
        ),
    ]
