# Generated by Django 4.1.3 on 2022-11-17 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non binary'), ('O', 'Other')], max_length=1)),
                ('in_vacation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state_province', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='travelers', to='agent.agent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler_country', to='catalogue.item')),
                ('phone_country_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler_phone_contry_code', to='catalogue.item')),
                ('traveler_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler_status', to='catalogue.item')),
            ],
            options={
                'db_table': 'travelers',
                'managed': True,
            },
        ),
    ]
