# Generated by Django 4.1.5 on 2023-01-09 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(default=None, null=True)),
                ('phone_country_code', models.CharField(default=None, max_length=5, null=True)),
                ('phone_number', models.CharField(default=None, max_length=10, null=True)),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('CH', 'Child')], default=None, max_length=2, null=True)),
                ('in_vacation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('city', models.CharField(default=None, max_length=200, null=True)),
                ('state_province', models.CharField(default=None, max_length=200, null=True)),
                ('zip_code', models.CharField(default=None, max_length=5, null=True)),
                ('passport', models.CharField(default=None, max_length=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='agent.agent')),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traveler_country', to='catalogue.country')),
                ('traveler_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_status', to='catalogue.item')),
            ],
            options={
                'db_table': 'travelers',
                'managed': True,
            },
        ),
    ]
