# Generated by Django 4.1.3 on 2022-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
