# Generated by Django 4.1.3 on 2022-11-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_item_slug'),
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='birthdate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='city',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler_country', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non binary'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='phone_country_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler_phone_contry_code', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='state_province',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='traveler_status',
            field=models.ForeignKey(default='ff82a0d3-7d21-4f8f-af9b-c28f61562749', on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler_status', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='zip_code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
