# Generated by Django 4.1.3 on 2022-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0002_alter_traveler_address_alter_traveler_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='gender',
        ),
        migrations.AddField(
            model_name='traveler',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
