# Generated by Django 4.1.3 on 2022-11-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_agent_agent_status_alter_agent_country_and_more'),
        ('catalogue', '0002_alter_item_catalogue'),
        ('traveler', '0002_traveler_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='agent.agent'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traveler_country', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='phone_country_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traveler_phone_contry_code', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='traveler_status',
            field=models.ForeignKey(default='ff82a0d3-7d21-4f8f-af9b-c28f61562749', on_delete=django.db.models.deletion.CASCADE, related_name='traveler_status', to='catalogue.item'),
        ),
    ]
