# Generated by Django 4.1.3 on 2022-11-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_alter_traveler_agent_alter_traveler_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('CH', 'Child')], default=None, max_length=2, null=True),
        ),
    ]
