# Generated by Django 4.1.4 on 2022-12-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_destination_search_field'),
        ('traveler', '0004_alter_traveler_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traveler_country', to='catalogue.country'),
        ),
    ]
