# Generated by Django 4.1.4 on 2022-12-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0005_alter_traveler_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveler',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
