# Generated by Django 4.1.4 on 2022-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0006_rename_birthdate_traveler_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='zip_code',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
