# Generated by Django 4.1.4 on 2022-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0007_alter_traveler_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='passport',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='zip_code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
