# Generated by Django 4.1.4 on 2022-12-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_country_metadata'),
        ('traveler', '0008_traveler_passport_alter_traveler_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='age',
        ),
        migrations.AlterField(
            model_name='traveler',
            name='traveler_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_status', to='catalogue.item'),
        ),
    ]
