# Generated by Django 4.1.3 on 2022-11-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
    ]
