# Generated by Django 4.1.3 on 2022-12-07 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iso_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['iso_code'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.country')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'db_table': 'destinations',
                'ordering': ['destination'],
                'managed': True,
            },
        ),
    ]
