# Generated by Django 4.1.4 on 2022-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_item_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='metadata',
            field=models.JSONField(default=None, null=True),
        ),
    ]
