# Generated by Django 4.1.3 on 2022-11-09 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.IntegerField()),
                ('check_in_date', models.DateField()),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('number_of_adults', models.PositiveIntegerField()),
                ('number_of_nights', models.PositiveIntegerField()),
                ('number_of_child', models.PositiveIntegerField()),
                ('hotel_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotels',
                'managed': True,
            },
        ),
    ]
