# Generated by Django 4.1.3 on 2022-11-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_latitude_alter_hotel_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': True, 'ordering': ['destination'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='hotelamenity',
            options={'managed': True, 'ordering': ['hotel'], 'verbose_name': 'Hotel amenity', 'verbose_name_plural': 'Hotel amenities'},
        ),
        migrations.AlterModelOptions(
            name='hotelpicture',
            options={'managed': True, 'ordering': ['hotel'], 'verbose_name': 'Hotel picture', 'verbose_name_plural': 'Hotel pictures'},
        ),
    ]
