# Generated by Django 4.1.5 on 2023-01-09 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('photo', models.URLField(default=None, null=True)),
                ('birthday', models.DateField(default=None, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('city', models.CharField(default=None, max_length=200, null=True)),
                ('state_province', models.CharField(default=None, max_length=200, null=True)),
                ('zip_code', models.CharField(default=None, max_length=5, null=True)),
                ('phone_country_code', models.CharField(default=None, max_length=5, null=True)),
                ('phone_number', models.CharField(default=None, max_length=20, null=True)),
                ('web_site', models.URLField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_status', models.ForeignKey(default='69e5e698-a900-4d14-a077-ba165f476a40', on_delete=django.db.models.deletion.CASCADE, related_name='agent_status', to='catalogue.item')),
                ('agent_subscription', models.ForeignKey(default='20179d75-765c-471b-9d2e-6dac1c91bce8', on_delete=django.db.models.deletion.CASCADE, related_name='agent_subscription', to='catalogue.item')),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_country', to='catalogue.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_user', to='user.user')),
            ],
            options={
                'db_table': 'agents',
                'managed': True,
            },
        ),
    ]
