# Generated by Django 4.1.5 on 2023-01-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='name',
            new_name='full_name',
        ),
    ]
