# Generated by Django 4.1.3 on 2022-11-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_item_slug'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='agent',
            name='birthdate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_country', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_country_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_phone_country_code', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='web_site',
            field=models.URLField(default=None, null=True),
        ),
    ]
