# Generated by Django 4.1.3 on 2022-11-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.URLField(default=None, null=True),
        ),
    ]
