# Generated by Django 4.1.3 on 2022-11-28 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_item_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0003_agent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_status',
            field=models.ForeignKey(default='69e5e698-a900-4d14-a077-ba165f476a40', on_delete=django.db.models.deletion.CASCADE, to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_country', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_country_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_phone_country_code', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
