# Generated by Django 4.1.3 on 2022-11-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_item_catalogue'),
        ('agent', '0005_agent_agent_subscription_alter_agent_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_subscription',
            field=models.ForeignKey(default='20179d75-765c-471b-9d2e-6dac1c91bce8', on_delete=django.db.models.deletion.CASCADE, related_name='agent_subscription', to='catalogue.item'),
        ),
    ]
