# Generated by Django 4.1.4 on 2022-12-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_alter_agent_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
