# Generated by Django 4.1.4 on 2022-12-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_rename_birthdate_agent_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone_country_code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
