# Generated by Django 4.1.4 on 2022-12-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_alter_agent_phone_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='state_province',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='zip_code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
