# Generated by Django 4.1.5 on 2023-01-09 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('hotel_name', models.CharField(max_length=200)),
                ('stars', models.PositiveSmallIntegerField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('address', models.CharField(default=None, max_length=600, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('destination', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_destination', to='catalogue.destination')),
                ('provider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_provider', to='catalogue.item')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotels',
                'ordering': ['destination'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelPicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('P', 'Principal'), ('A', 'Any')], default='A', max_length=1)),
                ('url', models.URLField(max_length=600)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_pictures', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel picture',
                'verbose_name_plural': 'Hotel pictures',
                'db_table': 'hotels_pictures',
                'ordering': ['hotel'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity', models.CharField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_amenities', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel amenity',
                'verbose_name_plural': 'Hotel amenities',
                'db_table': 'hotels_amenities',
                'ordering': ['hotel'],
                'managed': True,
            },
        ),
    ]
