# Generated by Django 4.1.3 on 2022-11-17 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=200)),
                ('stars', models.PositiveSmallIntegerField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_destination', to='catalogue.item')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotels',
                'ordering': ['destination'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelPicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_pictures', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel picture',
                'verbose_name_plural': 'Hotel pictures',
                'db_table': 'hotels_pictures',
                'ordering': ['hotel'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.item')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_amenities', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel amenity',
                'verbose_name_plural': 'Hotel amenities',
                'db_table': 'hotels_amenities',
                'ordering': ['hotel'],
                'managed': True,
            },
        ),
    ]
