# Generated by Django 4.1.3 on 2022-11-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_item_slug'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='hotelamenity',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_amenities', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelpicture',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_pictures', to='hotel.hotel'),
        ),
    ]
