# Generated by Django 4.1.3 on 2022-12-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_item_parent'),
        ('hotel', '0002_alter_hotel_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_code',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='external_id',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_destination', to='catalogue.item'),
        ),
    ]
