# Generated by Django 4.1.3 on 2022-12-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotelamenity_amenity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='adress',
            new_name='address',
        ),
    ]
