# Generated by Django 4.1.3 on 2022-12-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_item_parent'),
        ('hotel', '0005_rename_adress_hotel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_provider', to='catalogue.item'),
        ),
    ]
