# Generated by Django 4.1.3 on 2022-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpicture',
            name='image_type',
            field=models.CharField(choices=[('P', 'Principal'), ('A', 'Any')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
