# Generated by Django 4.1.3 on 2022-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hotelpicture_image_type_alter_hotel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpicture',
            name='url',
            field=models.URLField(max_length=600),
        ),
    ]
