# Generated by Django 4.1.3 on 2022-12-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_hotelpicture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country_code',
        ),
    ]
