# Generated by Django 4.1.4 on 2022-12-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_country_remove_item_metadata_remove_item_parent_and_more'),
        ('hotel', '0009_remove_hotel_city_remove_hotel_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_destination', to='catalogue.destination'),
        ),
    ]
