# Generated by Django 4.1.5 on 2023-01-09 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('hotel', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policies', models.JSONField(default=None, null=True)),
                ('policies_acceptance', models.BooleanField(default=False)),
                ('search_parameters', models.JSONField()),
                ('booking_response', models.JSONField(default=None, null=True)),
                ('booking_code', models.CharField(default=None, max_length=200, null=True)),
                ('confirmation_number', models.CharField(default=None, max_length=200, null=True)),
                ('cancelled_at', models.DateTimeField(default=None, null=True)),
                ('cancellation_response', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_payment', to='payment.payment')),
                ('reservation_status', models.ForeignKey(default='39810fb8-7302-41aa-9939-e0d867513fd9', on_delete=django.db.models.deletion.CASCADE, to='catalogue.item')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('supplements', models.JSONField(default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rooms', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'Reservation Rooms',
                'verbose_name_plural': 'Reservation Rooms',
                'db_table': 'reservation_rooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_lead', models.BooleanField()),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_guests', to='reservation.room')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'db_table': 'guests',
                'managed': True,
            },
        ),
    ]
