# Generated by Django 4.1.4 on 2022-12-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_code',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
