# Generated by Django 4.1.4 on 2022-12-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='policies',
            field=models.JSONField(default=None, null=True),
        ),
    ]
