# Generated by Django 4.1.4 on 2022-12-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_room_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='policies',
        ),
        migrations.AddField(
            model_name='reservation',
            name='policies',
            field=models.JSONField(default=None, null=True),
        ),
    ]
