# Generated by Django 4.1.4 on 2022-12-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_response',
            field=models.JSONField(default=True, null=True),
        ),
    ]
