# Generated by Django 4.1.4 on 2022-12-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_reservation_booking_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_resposne',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
