# Generated by Django 4.1.4 on 2022-12-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_reservation_cancellation_resposne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_response',
            field=models.JSONField(default=None, null=True),
        ),
    ]
