# Generated by Django 4.1.4 on 2022-12-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_reservation_booking_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='cancellation_resposne',
            new_name='cancellation_response',
        ),
    ]
