# Generated by Django 4.1.4 on 2022-12-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_rename_cancellation_resposne_reservation_cancellation_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='supplements',
            field=models.JSONField(default=None, null=True),
        ),
    ]
