# Generated by Django 4.1.4 on 2022-12-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_remove_reservation_supplements_room_supplements'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_number',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
